spring:
    application:
        name: magic-java-server
    main:
        allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。


    profiles:
        active: local


    # Servlet 配置
    servlet:
        # 文件上传相关配置项
        multipart:
            max-file-size: 16MB # 单个文件大小
            max-request-size: 32MB # 设置总上传的文件大小

    # cache 缓存配置
    cache:
        type: redis
        redis:
            time-to-live: 1h # 设置过期时间为 1 小时
    #        cache:
    #            # 缓存类型，默认为 ehcache
    #            type: redis
    #            redis:
    #                time-to-live: 1h # 设置过期时间为 1 小时

    # redis 配置
    redis:
        host: localhost
        port: 6379
        password: # 如果Redis服务器设置了密码，请在这里填写
        database: 0 # 数据库索引

    #  swagger文档配置
    mvc:
        static-path-pattern: /**
        pathmatch:
            matching-strategy: ant_path_matcher
    #  web 配置
    web:
        resources:
            static-locations: classpath:/static/ # 静态资源文件路径配置，多个路径用逗号分隔。优先级从上到下。

#################### flyway 配置 ##########
    flyway:
        # 是否启用，默认为 true
        enabled: true
        # 编码格式，默认UTF-8
        encoding: UTF-8
        # sql脚本存放路径，默认 db/migration
        locations: classpath:db/migration
        # sql脚本文件名前缀，默认V
        sql-migration-prefix: V
        # sql脚本文件名分隔符，默认双下划线__
        sql-migration-separator: __
        # sql脚本文件名称的后缀，默认.sql
        sql-migration-suffixes: .sql
        # 是否替换sql脚本中的占位符，占位符默认是${xxx},默认是替换，如果不需要替换，可以设置为false
        placeholder-replacement: false
        # 迁移时是否进行校验，确保历史脚本未篡改，默认true
        validate-on-migrate: true
        # 设置为false会删除指定schema下所有的表，生产环境务必禁用，spring中该参数默认是false，需要手动设置为true
        clean-disabled: true
        # 当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建schema_version表
        baseline-on-migrate: true
        # 基准版本，默认0
        baseline-version: 1.0.0

#################### server servlet 配置 ##########
server:
    servlet:
        encoding:
            enabled: true
            charset: UTF-8 # 必须设置 UTF-8，避免 WebFlux 流式返回乱码问题
            force: true
#################### log 日志配置 ##########
logging:
    level:
        root: error
        org.springframework: info
        org.springframework.security: debug

#################### mybatis-plus配置 ####################

mybatis-plus:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.magic.module.*.entity
    global-config:
        db-config:
            id-type: auto
            table-prefix: t_
            logic-delete-value: 1
            logic-not-delete-value: 0
    configuration:
        map-underscore-to-camel-case: true

#################### magic server 项目通用配置 ##########
magic:
    storage:
        aliyun:
            enabled: false # 是否启用阿里云OSS存储
        local:
            enabled: true # 是否启用本地OSS存储
    ecsFilePath: /data/web/dist/h5games/  # ECS存储
    lock:
        type: redis # 锁类型，支持 redis、mysql
